from __future__ import annotations
from typing import Any, Dict

MESSAGES: Dict[str, Dict[str, str]] = {
    "en": {
        "report.title": "PRISM Report",
        "report.subtitle": "OSINT Reconnaissance Report",
        "report.target": "Target",
        "report.scanType": "Scan type",
        "report.generated": "Generated",
        "report.footer": "Generated by PRISM OSINT Toolkit",

        "opsec.score": "OPSEC Score",
        "opsec.risk": "{level} RISK",
        "opsec.findings": "Security Findings ({n})",
        "opsec.cat.data_exposure": "Data Exposure",
        "opsec.cat.identity_opsec": "Identity OPSEC",
        "opsec.cat.infrastructure": "Infrastructure",
        "opsec.cat.web_security": "Web Security",
        "opsec.points": "pts",

        "whois.title": "WHOIS",
        "whois.registrar": "Registrar",
        "whois.organization": "Organization",
        "whois.created": "Created",
        "whois.expires": "Expires",
        "whois.country": "Country",
        "whois.nameServers": "Name servers",

        "dns.title": "DNS",

        "geoip.title": "GeoIP",
        "geoip.ip": "IP",
        "geoip.city": "City",
        "geoip.country": "Country",
        "geoip.organization": "Organization",
        "geoip.coordinates": "Coordinates",

        "subdomains.title": "Subdomains ({n})",
        "subdomains.more": "… and {n} more",

        "accounts.title": "Accounts found ({n})",
        "accounts.site": "Site",
        "accounts.url": "URL",

        "virustotal.title": "VirusTotal",
        "virustotal.malicious": "Malicious",
        "virustotal.suspicious": "Suspicious",
        "virustotal.harmless": "Harmless",
        "virustotal.reputation": "Reputation",

        "abuseipdb.title": "AbuseIPDB",
        "abuseipdb.confidence": "Confidence score",
        "abuseipdb.totalReports": "Total reports",
        "abuseipdb.country": "Country",
        "abuseipdb.isp": "ISP",

        "shodan.title": "Shodan",
        "shodan.ip": "IP",
        "shodan.organization": "Organization",
        "shodan.os": "OS",
        "shodan.openPorts": "Open ports",

        "breaches.title": "Email breaches ({n})",
        "breaches.source": "Source",
        "breaches.date": "Date",

        "phone.title": "Phone",
        "phone.valid": "Valid",
        "phone.country": "Country",
        "phone.carrier": "Carrier",
        "phone.lineType": "Line type",
        "phone.region": "Region",
    },
    "ru": {
        "report.title": "Отчёт PRISM",
        "report.subtitle": "Отчёт по OSINT-разведке",
        "report.target": "Цель",
        "report.scanType": "Тип скана",
        "report.generated": "Сформирован",
        "report.footer": "Сгенерировано PRISM OSINT Toolkit",

        "opsec.score": "Оценка OPSEC",
        "opsec.risk": "{level} РИСК",
        "opsec.findings": "Находки безопасности ({n})",
        "opsec.cat.data_exposure": "Утечки данных",
        "opsec.cat.identity_opsec": "OPSEC личности",
        "opsec.cat.infrastructure": "Инфраструктура",
        "opsec.cat.web_security": "Web-безопасность",
        "opsec.points": "очк",

        "whois.title": "WHOIS",
        "whois.registrar": "Регистратор",
        "whois.organization": "Организация",
        "whois.created": "Создан",
        "whois.expires": "Истекает",
        "whois.country": "Страна",
        "whois.nameServers": "DNS-серверы",

        "dns.title": "DNS",

        "geoip.title": "GeoIP",
        "geoip.ip": "IP",
        "geoip.city": "Город",
        "geoip.country": "Страна",
        "geoip.organization": "Организация",
        "geoip.coordinates": "Координаты",

        "subdomains.title": "Поддомены ({n})",
        "subdomains.more": "… и ещё {n}",

        "accounts.title": "Найдено аккаунтов ({n})",
        "accounts.site": "Сайт",
        "accounts.url": "URL",

        "virustotal.title": "VirusTotal",
        "virustotal.malicious": "Зловреды",
        "virustotal.suspicious": "Подозрительно",
        "virustotal.harmless": "Безопасно",
        "virustotal.reputation": "Репутация",

        "abuseipdb.title": "AbuseIPDB",
        "abuseipdb.confidence": "Уровень злоупотребления",
        "abuseipdb.totalReports": "Всего жалоб",
        "abuseipdb.country": "Страна",
        "abuseipdb.isp": "Провайдер",

        "shodan.title": "Shodan",
        "shodan.ip": "IP",
        "shodan.organization": "Организация",
        "shodan.os": "ОС",
        "shodan.openPorts": "Открытые порты",

        "breaches.title": "Утечки e-mail ({n})",
        "breaches.source": "Источник",
        "breaches.date": "Дата",

        "phone.title": "Телефон",
        "phone.valid": "Валиден",
        "phone.country": "Страна",
        "phone.carrier": "Оператор",
        "phone.lineType": "Тип линии",
        "phone.region": "Регион",
    },
    "de": {
        "report.title": "PRISM-Bericht",
        "report.subtitle": "OSINT-Aufklärungsbericht",
        "report.target": "Ziel",
        "report.scanType": "Scan-Typ",
        "report.generated": "Erstellt",
        "report.footer": "Erstellt von PRISM OSINT Toolkit",

        "opsec.score": "OPSEC-Bewertung",
        "opsec.risk": "{level} RISIKO",
        "opsec.findings": "Sicherheits-Befunde ({n})",
        "opsec.cat.data_exposure": "Datenexposition",
        "opsec.cat.identity_opsec": "Identitäts-OPSEC",
        "opsec.cat.infrastructure": "Infrastruktur",
        "opsec.cat.web_security": "Web-Sicherheit",
        "opsec.points": "Pkt",

        "whois.title": "WHOIS",
        "whois.registrar": "Registrar",
        "whois.organization": "Organisation",
        "whois.created": "Erstellt",
        "whois.expires": "Läuft ab",
        "whois.country": "Land",
        "whois.nameServers": "Nameserver",

        "dns.title": "DNS",

        "geoip.title": "GeoIP",
        "geoip.ip": "IP",
        "geoip.city": "Stadt",
        "geoip.country": "Land",
        "geoip.organization": "Organisation",
        "geoip.coordinates": "Koordinaten",

        "subdomains.title": "Subdomains ({n})",
        "subdomains.more": "… und {n} weitere",

        "accounts.title": "Gefundene Konten ({n})",
        "accounts.site": "Seite",
        "accounts.url": "URL",

        "virustotal.title": "VirusTotal",
        "virustotal.malicious": "Schädlich",
        "virustotal.suspicious": "Verdächtig",
        "virustotal.harmless": "Harmlos",
        "virustotal.reputation": "Reputation",

        "abuseipdb.title": "AbuseIPDB",
        "abuseipdb.confidence": "Missbrauchs-Score",
        "abuseipdb.totalReports": "Gesamtmeldungen",
        "abuseipdb.country": "Land",
        "abuseipdb.isp": "ISP",

        "shodan.title": "Shodan",
        "shodan.ip": "IP",
        "shodan.organization": "Organisation",
        "shodan.os": "Betriebssystem",
        "shodan.openPorts": "Offene Ports",

        "breaches.title": "E-Mail-Leaks ({n})",
        "breaches.source": "Quelle",
        "breaches.date": "Datum",

        "phone.title": "Telefon",
        "phone.valid": "Gültig",
        "phone.country": "Land",
        "phone.carrier": "Anbieter",
        "phone.lineType": "Anschlussart",
        "phone.region": "Region",
    },
}

SUPPORTED_LANGS = tuple(MESSAGES.keys())


def get_messages(lang: str | None) -> Dict[str, str]:
    if not lang:
        return MESSAGES["en"]
    key = lang.lower().split("-")[0].strip()
    return MESSAGES.get(key, MESSAGES["en"])


def make_translator(lang: str | None):
    msgs = get_messages(lang)

    def t(key: str, **kwargs: Any) -> str:
        s = msgs.get(key) or MESSAGES["en"].get(key) or key
        if kwargs:
            for k, v in kwargs.items():
                s = s.replace("{" + k + "}", str(v))
        return s

    return t
